mode_id_to_name = ["MANUAL", "CIRCLE", "STABILIZE", "TRAINING", "ACRO", "FBWA", "FBWB", "CRUISE", "AUTOTUNE", "AUTO", "RTL", "LOITER", "AVOID_ADSB", "GUIDED", "QSTABILIZE", "QHOVER", "QLOITER", "QLAND", "QRTL", "UNKNOWN"]

FMT_BYTE = "!B"
FMT_INT = "!i"
FMT_UINT = "!I"
FMT_USHORT = "!H"

MSG_TYPE_MAVLINK = 0
MSG_TYPE_RADIO = 1
MSG_TYPE_RADIO_ERROR = 2

MSG_TYPE_PING_REQUEST = 3
MSG_TYPE_PING_RESPONSE = 4

MSG_TYPE_VIDEO_LOW = 5
MSG_TYPE_VIDEO_MED = 6
MSG_TYPE_VIDEO_HIGH = 7

MSG_TYPE_SET_FLIGHT_MODE = 8
